### ISSUE TITLE
iCal Password Setting is misleading

### ISSUE THREAD

**Issue by frereit** [DU4L/CTFNote#45]
Currently the admin dashboard allows the admins to set a password for the iCal. Because this password is then used for the api:3000/calendar.ics endpoint, it won't actually affect the public facing ical-relay:8080/profiles/du4lcombined endpoint. Instead that endpoint will just fail to fetch the CTF events and either crash or just not display those events.

We should just remove the key here imo and consider adding an optional key for the iCal relay (or just rename the profile and use the profile name as the key, easiest solutions imo)

**Comment by JM-Lemmi** [comment]
I've been wanting to add that kind of functionality to ical-relay. There is a config item called public, but I don't know if it even does something.

**Comment by JM-Lemmi** [comment]
Now that we removed the ical-relay, this issue is meaningless.
