### ISSUE TITLE
Use yarn workspaces

### ISSUE THREAD

**Issue by JM-Lemmi** [DU4L/CTFNote#46]
- [ ] If this works with our docker containers?

https://classic.yarnpkg.com/lang/en/docs/workspaces/

> All your project dependencies will be installed together, giving Yarn more latitude to better optimize them.

**Comment by frereit** [comment]
I don't think this fits well with the structure of the containers.

The API and Frontend are seperate by design, this would require that they have a shared volume. I personally think it's not really useful enough to justify giving up the clean separation of api/frontend

**Comment by JM-Lemmi** [comment]
Alright.
