### ISSUE TITLE
calender as a ical

### ISSUE THREAD

**Issue by ElevenSpins** [DU4L/CTFNote#9]
posiibility to add the calender to your local device

**Comment by JM-Lemmi** [comment]
Maybe add with RSVP options

**Comment by ElevenSpins** [comment]
Don't Know in we a rsvp need… a simple Positivliste to add Events and the possibility to Subskribent the cal is enought.

**Comment by frereit** [comment]
How should this be authenticated? Having to set a cookie to get the calendar is very ugly.
We could generate a unique, never expiring, `ical_token` for each user, then each user can request the calendar with `ctfnote/ical?token=abcdefgh`?
Or just don't authenticated at all?

**Comment by JM-Lemmi** [comment]
Since the data is also availible publicly on our discord, I don't think authentication is necessary.

**Comment by frereit** [comment]
> I don't think authentication is necessary.

This was surprisingly easy, see  ed21487 

RSVP is a bit more complicated, as far as I understand it RSVP works over E-mail? Not exactly sure, maybe you can help here @JM-Lemmi? Also the library i used doesn't have any RSVP support so we'd have to chose a different one or do it 'manually'

**Comment by JM-Lemmi** [comment]
RSVP is usually just a line called `ORGANIZER:` in the VEVENT

I can have a quick look tomorrow. But don't let that hold you up.

**Comment by JM-Lemmi** [comment]
I did also look into connecting it with the Discord calendar, but the projects I found were not fully convincing.

**Comment by frereit** [comment]
> RSVP is usually just a line called ORGANIZER: in the VEVENT

good shout, didn't know this. Organizer is a field that exists in the library, will look into this

**Comment by JM-Lemmi** [comment]
Okay, @frereit and I just discussed a bit about this feature going forward:

- Easier management for non-CTF entries can be done by having a **shared Outlook calendar**, that the "admins" can edit. This calendar is shared via private ical link.
- CTFNote offers ical for the entered CTFs, drawn from CTFtime.
- There is an admin interface that allows add any other internet ical links
- These icals will all be combined by [JMLemmi/ical-relay](https://github.com/JM-Lemmi/ical-relay) that offers the public ical for all members
